name: Test workflow
on:
  push:
  workflow_dispatch:

jobs:
  js_ecoshitstem:
    strategy:
      matrix:
        node-version: [18, 20]
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Use Node.js latest
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: echo 'hi' >'file name.txt'
    - shell: bash
      run: |
        cat <<EOF >script.mjs
          import {readFile} from "node:fs/promises";
          import {resolve} from "node:path";
          import {fileURLToPath} from "node:url";

          function unfuck(url) {
            let resolved = url.pathname;
            if (url.protocol !== 'file:') {
              // in webpack we aren't even getting a valid URL
              resolved = resolve(resolved)
            }

            const path = fileURLToPath("file://" + resolved);
            console.log(url, resolved, path);

            readFile(path).then(console.log.bind(console), console.error.bind(console));
          }

          unfuck(new URL("file name.txt", import.meta.url)); // this is what unbundled code looks like
          unfuck({ pathname: "file name.txt" }); // this is what bundling with nextjs will give us
        EOF
    - run: node script.mjs
