name: Windows workflow
on:
  workflow_dispatch:

jobs:
  brr:
    strategy:
      matrix:
        node-version: [18, 20, 21]
    runs-on: windows-latest
    steps:
    - name: Use Node.js latest
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: echo 'hi' >file.txt
    - run: node --input-type=module -e 'import {readFile} from "node:fs/promises"; import {resolve} from "node:path"; import {fileURLToPath} from "node:url"; const url=new URL("file.txt", import.meta.url); console.log(url, url.pathname, resolve(url.pathname), fileURLToPath("file://" + resolve(url.pathname))); readFile(fileURLToPath("file://" + resolve(url.pathname))).then(console.log.bind(console), console.error.bind(console));'
